name: Lint Python code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting tools
        run: |
          pip install black flake8 isort

      # - name: Check code style with Black
      #   run: black --check app tests setup scripts

      # - name: Check import order with isort
      #   run: isort --check-only app tests setup scripts

      - name: Lint with Flake8
        run: flake8 app tests setup scripts --ignore=E501
